# Generated by Django 2.0.5 on 2018-06-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
    ]
