image: python:3.6

services:
  - name: mdillon/postgis:10-alpine
    alias: postgres

cache:
  paths:
    - .cache/

variables:
  POSTGRES_DBNAME: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  DJANGO_SETTINGS_MODULE: config.settings.test
  SECRET_KEY: secret
  DB_HOST: postgres
  DB_NAME: postgres
  DB_USER: postgres
  DB_PASSWORD: postgres
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

stages:
  - lint
  - test

python_linter:
  stage: lint
  image: python:3.6
  script:
    - pip install poetry
    - poetry install
    - poetry run flake8 .
    - poetry run black --check .

python_test:
  stage: test
  script:
    - apt-get update && apt-get install binutils libproj-dev gdal-bin -y
    - pip install poetry
    - poetry install
    - poetry run pytest --cov
